pull_request_rules:
  - name: Automatic merge when required reviews are approved
    conditions:
      - base=develop
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: merge
