# # NOTICE
# 
# ## Before Committing
# 1. Verify the validity of the configuration via the following shell command;
#   ```shell
#   cat codecov.yml | curl --data-binary @- https://codecov.io/validate
#   ```

codecov:
  token: "secret:MV/bbQs7G9pJMr9d23PBUd+s6PP3MMj3RGqwOIWIlUH4639jfrTi+CxbHTBhicskHyYRuaDoTLB+HbktHuxYftPEC+MLacZJAn3krVe2jj8="
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes

coverage:
  range: 50..90
  round: nearest
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0%
        flags:
          - unit
        paths:
          - "src"
        #branches:
          #- main
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch: false
