# Before making changes to this file, please verify it validity with the
# following shell command;
# `cat codecov.yml | curl --data-binary @- https://codecov.io/validate`.

codecov:
  token: "secret:xGpGvas82nUNsQ5qjyZYJEjdBwsbX0E6m93vHgzlLSRfD1IVsVrlcQDYsb6ooJx4gEJcVN+UHpoHS6NOmLJF7LTiKEd7bdLgUNMkuKK78Rs="
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: false
  require_ci_to_pass: true
  notify:
    after_n_builds: 2
    wait_for_ci: true

coverage:
  range: 50..90
  round: nearest
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0%
        flags:
          - unit
        paths:
          - "src/**"
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch: false

github_checks:
  annotations: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
