# -------------
# | Variables |
# -------------
[env]
# This variable will vary depending on where you installed Worlds, ideally, you
# should know the correct value for your own system.
#
# If you DON'T know the correct value, DO NOT file an issue on GitHub, ask
# someone within the Whirlsplash Discord server;
# https://discord.com/invite/8hn6padWF6.
#
# See line 49!
WORLDS_PATH = "C:\\Program Files (x86)\\Worlds Inc\\WorldsPlayer - Win7\\WorldsPlayer.exe"

# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]

[tasks.help]
dependencies = ["checkf"]
command = "cargo"
args = ["run", "--", "help"]

[tasks.run]
dependencies = ["checkf"]
command = "cargo"
args = ["run", "--", "run"]

# This task also depends on your system configuration, same goes as read above.
[tasks.start-client]
command = "gsudo"
args = ["${WORLDS_PATH}"]

[tasks.runc]
dependencies = ["start-client", "run"]

[tasks.runw]
env = { "DISABLE_PROMPT" = true }
dependencies = ["checkf"]
command = "cargo"
args = ["run", "--", "run"]
watch = true

[tasks.docker-build]
command = "nix-build"
args = ["docker.nix"]

[tasks.docker-load]
script_runner = "@shell"
script = '''
docker load < result
'''

[tasks.docker-run]
command = "docker"
args = [
  "run",
  "--name", "Whirlsplash",
  #     API                Distributor        Hub
  "-p", "8000:8000", "-p", "6650:6650", "-p", "5673:5673",
  "whirlsplash/whirl"
]

# Build 'n' load
[tasks.bnl]
dependencies = ["docker-build", "docker-load"]

