# -------------
# | Variables |
# -------------
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
EXIT_ON_CLIENT_DISCONNECT = true

# This variable will vary depending on where you installed Worlds, ideally, you
# should know the correct value for your own system.
#
# If you DON'T know the correct value, DO NOT file an issue on GitHub, ask
# someone within the Whirlsplash Discord server;
# https://discord.com/invite/8hn6padWF6.
#
# See line 56!
WORLDS_PATH = "C:\\Program Files (x86)\\Worlds Inc\\WorldsPlayer - Win7\\WorldsPlayer.exe"

# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]
private = true

[tasks.check]
command = "cargo"
args = ["check"]
private = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]
private = true

# -------------
# | Executors |
# -------------
[tasks.checkf]
workspace = false
dependencies = ["fmt", "check"]

[tasks.checkfc]
workspace = false
dependencies = ["fmt", "check", "clippy"]

[tasks.help]
workspace = false
dependencies = ["checkf"]
command = "cargo"
args = ["run", "--", "help"]

[tasks.run]
workspace = false
dependencies = ["checkf"]
command = "cargo"
args = ["run", "--", "run"]

# This task also depends on your system configuration, same goes as read above.
[tasks.start-client]
workspace = false
command = "gsudo"
args = ["${WORLDS_PATH}"]

[tasks.runc]
workspace = false
dependencies = ["start-client", "run"]

[tasks.runw]
workspace = false
env = { "DISABLE_PROMPT" = true }
dependencies = ["checkf"]
command = "cargo"
args = ["run", "--", "run"]
watch = true

[tasks.docker-build]
workspace = false
command = "nix-build"
args = ["docker.nix"]

[tasks.docker-load]
workspace = false
script_runner = "@shell"
script = '''
docker load < result
'''

[tasks.docker-run]
workspace = false
command = "docker"
args = [
  "run",
  "--name", "Whirlsplash",
  #     API                Distributor        Hub
  "-p", "8000:80", "-p", "6650:6650", "-p", "5673:5673",
  "whirlsplash/whirl"
]

[tasks.docker-run-i]
workspace = false
command = "docker"
args = [
  "run",
  "-it",
  "--name", "Whirlsplash",
  #     API                Distributor        Hub
  "-p", "8000:80", "-p", "6650:6650", "-p", "5673:5673",
  "--env", "DISABLE_PROMPT=false",
  "whirlsplash/whirl"
]

# Build 'n' load
[tasks.bnl]
workspace = false
dependencies = ["docker-build", "docker-load"]

[tasks.ask-github-token]
workspace = false
script = '''
#!@duckscript

echo github token:
github_token = read

echo set ${github_token} as the current github token
set_env GITHUB_TOKEN ${github_token}
'''

[tasks.act]
workspace = false
dependencies = ["ask-github-token"]
command = "act"
args = ["-s", "GITHUB_TOKEN=${GITHUB_TOKEN}"]
