# See more keys and their definitions at https://whirlsplash.org/docs/whirl/configuration

[whirlsplash]
worldsmaster_username = "WORLDSMASTER"
ip = "0.0.0.0"
api.port = 8080

[whirlsplash.prompt]
enable = false
ps1 = "[WORLDSMASTER@Whirlsplash ~]$"

[whirlsplash.log]
enable = true
level = 1
everything = false
test = false

[distributor]
worldsmaster_greeting = "Welcome to Whirlsplash!"
port = 6650

[hub]
port = 5673
