[whirlsplash]
worldsmaster_username = "WORLDSMASTER" # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING
ip = "0.0.0.0" # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING
api.port = 8080

[whirlsplash.prompt]
enable = false
ps1 = "[WORLDSMASTER@Whirlsplash ~]$"

[whirlsplash.log]
enable = true
level = 1
everything = false
test = false

[distributor]
worldsmaster_greeting = "Welcome to Whirlsplash!"
port = 6650 # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING

[hub]
port = 5673 # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING
