name: Audit 🩺


on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v2

      - name: Audit 🩺
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ github.token }}
